# travis-ci.org build & test configuration
sudo: required

language: python

services:
  - docker

before_install:
  - docker pull hepsw/cvmfs-cms
  - sudo mkdir /software && sudo chown $USER /software

install:
 - source bin/env.sh

script:
  - nosetests -vs python/ntp/test
  - ./test/test.sh
  - sudo docker build -t kreczko/ntp .
  - sudo docker run -t -v /software:/software --privileged=true kreczko/ntp
cache: apt
